# For local development
version: '3.3'
services:

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=eventus
      - POSTGRES_PASSWORD=eventus
      - POSTGRES_DB=eventus

  eventus:
    container_name: coursework
    build:
      context: ./target/docker/stage/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - EVENTUS_DB_URL=jdbc:postgresql://localhost:5432/eventus
      - EVENTUS_DB_USER=eventus
      - EVENTUS_DB_PASS=eventus
      - EVENTUS_HTTP_PORT=8080
      - EVENTUS_LOG_LEVEL=ERROR
      - EVENTUS_EMAIL_HOST=your.smtp.host
      - EVENTUS_EMAIL_PORT=465
      - EVENTUS_EMAIL_USER=your@ema.il
      - EVENTUS_EMAIL_PASS=secret
    network_mode: "host"
    depends_on:
      - postgres
